#: import menu menu

MainWidget:

<MainWidget>:
    canvas.before:
        Rectangle:
            size: self.size
            source: 'images/bg1.jpg'
    menu_widget: menu_widget
    perspective_point_x: self.width/2
    perspective_point_y: self.height * .75
    Label:
        text: root.score_text
        font_size: "30dp"
        pos_hint: {"x": 0, "top": 1}
        font_name: "fonts/Eurostile.ttf"
        size_hint: .2, .2
    MenuWidget:
        id: menu_widget